service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  create-token:
    handler: index.tokenizerCreateTokenHandler
    events:
      - httpApi:
          path: /api/tokenizer/create-token
          method: POST
  get-card-info:
    handler: index.tokenizerGetCardDataHandler
    events:
      - httpApi:
          path: /api/tokenizer/card-info/{token}
          method: get
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin