service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  # environment:
  #   DB_HOST: ${file(.env):DB_HOST}
  #   DB_PORT: ${file(.env):DB_PORT}
  #   TOKENIZER_EXPIRATION_TOKEN: ${file(.env):TOKENIZER_EXPIRATION_TOKEN}

functions:
  create-token:
    handler: index.tokenizerCreateTokenHandler
    events:
      - httpApi:
          path: /api/tokenizer/create-token
          method: POST
  get-card-info:
    handler: index.tokenizerGetCardDataHandler
    events:
      - httpApi:
          path: /api/tokenizer/card-info/{token}
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin